rule all:
    input:
        "figure.png"

rule plot:
    input:
        "decay_observed.csv"
    output:
        "figure.png"
    shell:
        "python plot.py"

rule clean:
    shell:
        "rm -f figure.png"